export {
  deleteBookScripture,
  deleteChapterScripture,
  deleteLanguageScripture,
  downloadBookScripture,
  downloadChapterScripture,
  downloadLanguageScripture,
  getBookScriptureFileSizeBytes,
  getChapterScriptureFileSizeBytes,
  getDownloadedBookByteSize,
  getDownloadedChapterScriptureByteSize,
  getLanguageDownloadedByteSize,
  getLanguageScriptureTotalBytes,
  getOfflineChapterHtml,
  getOfflineChapterNumbers,
  hasStandaloneChapterScripture,
  isBookDownloaded,
  isChapterScriptureDownloaded,
  isLanguageScriptureDownloaded,
  loadWholeBookChapters,
  resolveBookContent,
} from './offline-text/index';
export type { DownloadProgressCallback } from './offline-text/index';
